import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const CERT_LINKS = {
  html: 'https://progate.com/course_certificate/431608c5r40h2n',
  python: 'https://progate.com/course_certificate/9d8ba627r23ac7',
  dpr: 'https://drive.google.com/file/d/17Cha63VtCPyopWSzmsSGtP-FEfnPNuq1/preview',
  bootcamp: null,
  devtown1: 'https://cert.devtown.in/verify/Zgvlvx',
  codepolitan: 'https://www.codepolitan.com/c/XOYCKI4/',
};

// ─── CV file paths per language ───────────────────────────────────────────────
const CV_FILES = {
  en: '/cv/CV26-Ryan-EN.pdf',
  id: '/cv/CV26-Ryan-EN.pdf',
  de: '/cv/CV26-Ryan-DE.pdf',
};

// ─── project tech tags (language-agnostic) ───────────────────────────────────
const TECH = {
  nuansaGrafika: ['React', 'Tailwind', 'Framer Motion', 'JavaScript'],
  careerPortal: ['Vue.js', 'Laravel', 'MySQL', 'Tailwind'],
  newsPortal: ['Laravel', 'MySQL', 'Tailwind', 'PHP', 'Figma'],
  electionSystem: ['React', 'Node.js', 'Express', 'MongoDB', 'Socket.io', 'JWT'],
  onlineCourse: ['React', 'JavaScript', 'Tailwind', 'Node.js', 'Express', 'MySQL'],
  portfolio: ['React', 'JavaScript', 'Tailwind', 'GSAP'],
  chill: ['HTML5', 'CSS3', 'JavaScript'],
  todolist: ['HTML5', 'CSS3', 'JavaScript'],
  odrin: ['Kotlin', 'SQLite'],
  cinema: ['Java'],
};

const SRC = {
  nuansaGrafika: '/img/project/nuansa.png',
  careerPortal: '/img/project/career.png',
  newsPortal: '/img/project/news-portal.png',
  electionSystem: '/img/project/election.png',
  onlineCourse: '/img/project/videobelajar.png',
  portfolio: '/img/project/porto.png',
  chill: '/img/project/chill.png',
  todolist: '/img/project/todolist.png',
  odrin: '/img/project/odrin.png',
  cinema: '/img/project/java-ticket.png',
};

export const translations = {
  // ══════════════════════════════════════════════════════════════════════ EN ══
  en: {
    nav: { home: 'Home', about: 'About', projects: 'Projects' },

    home: {
      role: 'Fullstack Developer',
      description: 'Bachelor of Information Computer Technology · Asia e University. Experienced in full-stack web and mobile development. Recently completed a Fullstack Web Bootcamp and German B1 language course.',
      resume: 'Résumé',
      contact: 'Contact Me',
      seeMore: 'Explore',
      cvFile: CV_FILES.en,
    },

    about: {
      title: 'About Me',
      subtitle: 'Fullstack Developer',
      tagline: 'Web & Mobile · Gamer · Cinema  ',
      certHint: '↑ Click a certificate to preview',
      downloadCV: 'Download CV',
      contact: 'Contact Me',
      profileAlt: 'Muhammad Ryan Cakraningrat',
      cvFile: CV_FILES.en,
      bio: 'An undergraduate in Information Computer Technology at Asia e University. I build full-stack web and mobile applications — from UI/UX prototyping to backend API and deployment. Deeply interested in clean architecture and some interesting UX. Currently deepening my programming skills through online courses and exploring homeserver usage for personal needs.',
      stats: { projects: 'Projects', internships: 'Work Exp.', certs: 'Certifications' },
      sections: {
        experience: 'Work Experience',
        education: 'Education',
        skills: 'Tech Stack',
        certifications: 'Certifications & Training',
      },
      experience: [
        {
          role: 'Frontend Web Developer',
          company: 'Nuansa Grafika',
          period: 'Sep 2025 – Dec 2025',
          desc: 'Designed and developed a fully static company profile website for a graphic design & printing company from scratch. Built the entire UI using React.js and Tailwind CSS with Framer Motion animations. Implemented 22 products across 9 filterable categories, infinite-scroll testimonials, FAQ accordion, embedded Google Maps, and a WhatsApp-based ordering CTA.',
          tags: ['React', 'Tailwind CSS', 'Framer Motion', 'JavaScript'],
        },
        {
          role: 'Fullstack Web Developer',
          company: 'Frisidea Tech',
          period: 'Sep 2024 – May 2025',
          desc: 'Built a career page web app from scratch (frontend, backend, admin panel) using Vue.js, Tailwind CSS, and Laravel 11. Deployed to live domain. Configured multi-project server infrastructure, engineered dynamic API integrations with senior devs, and improved mobile UX by 40% via responsive Tailwind patterns.',
          tags: ['Vue.js', 'Laravel 11', 'Tailwind', 'MySQL', 'API'],
        },
        {
          role: 'Freelance Fullstack Developer',
          company: 'Personal News Portal',
          period: 'Dec 2023 – Feb 2024',
          desc: 'Designed and developed a full-stack news portal from Figma prototyping to production using Laravel + Tailwind. Implemented trending categories, advanced search, video embeds, likes/comments, and a role-based admin panel (editor vs. administrator).',
          tags: ['Laravel', 'MySQL', 'Tailwind', 'Figma', 'RBAC'],
        },
        {
          role: 'Fullstack Android & Web Developer Intern',
          company: 'House of Representatives (DPR RI)',
          period: 'Jun 2023 – Jul 2023',
          desc: 'Built a native Android attendance app (Kotlin + REST API) and a web admin dashboard (CodeIgniter 4) for parliament operations. Optimized database schemas improving query performance by 35%.',
          tags: ['Kotlin', 'Android', 'CodeIgniter 4', 'MySQL', 'REST API'],
        },
      ],
      education: [
        {
          degree: 'Bachelor of ICT',
          school: 'Asia e University (Malaysia)',
          period: 'Sep 2021 – 2026',
          note: 'GPA 3.56 · Double-degree',
        },
        {
          degree: 'Diploma NIIT – Information Technology',
          school: 'CEP-CCIT, University of Indonesia',
          period: 'Sep 2021 – Sep 2023',
          note: 'GPA 3.00',
        },
        {
          degree: 'Fullstack Web Developer Bootcamp',
          school: 'Harisenin.com',
          period: 'May 2024 – Oct 2024',
          note: 'Completed · GPA 4.00',
        },
      ],
      skills: {
        frontend: ['React.js', 'Vue.js', 'Tailwind CSS', 'HTML5', 'CSS3', 'JavaScript', 'GSAP', 'Framer Motion'],
        backend: ['Laravel', 'CodeIgniter 4', 'Node.js', 'Express.js', 'PHP', 'Socket.io'],
        mobile: ['Kotlin', 'Java (Android)', 'Android Studio'],
        database: ['MySQL', 'SQLite', 'MongoDB'],
        tools: ['Git', 'Figma', 'REST API', 'JWT', 'Multer', 'AWS'],
      },
      languages: [
        { lang: 'Indonesian', level: 'Native' },
        { lang: 'English', level: 'Intermediate' },
        { lang: 'German', level: 'B1' },
      ],
      certifications: [
        { name: 'AWS re/Start Program', issuer: 'Amazon Web Services', year: '2025', previewLink: null },
        { name: 'Fullstack Developer Bootcamp', issuer: 'Harisenin.com', year: '2024', previewLink: null, id: 'HSBC/FSD/012/20241023049' },
        { name: 'HTML & CSS Basic Learning', issuer: 'Codepolitan', year: '2024', previewLink: CERT_LINKS.codepolitan },
        { name: 'Web Development Workshop', issuer: 'DevTown', year: '2023', previewLink: CERT_LINKS.devtown1 },
        { name: 'DPR RI Internship Certificate', issuer: 'House of Representatives', year: '2023', previewLink: CERT_LINKS.dpr },
        { name: 'Introduction to HTML & CSS', issuer: 'Progate', year: '2021', previewLink: CERT_LINKS.html },
        { name: 'Introduction to Python', issuer: 'Progate', year: '2021', previewLink: CERT_LINKS.python },
      ],
    },

    projects: {
      title: 'My Projects',
      label: 'Portfolio',
      items: [
        {
          id: 'nuansaGrafika',
          title: 'Nuansa Grafika — Company Profile',
          description: 'Fully static company profile website for a graphic design & printing company with animated product catalog.',
          detail:
            'Built from scratch with React.js and Tailwind CSS, featuring Framer Motion animations and a dynamic particle background. The platform manages a filterable catalog of 22 products across 9 categories, complete with infinite-scroll testimonials, FAQ sections, and Google Maps integration. I engineered a WhatsApp-based ordering system with product-specific CTAs and a floating contact button to streamline inquiries. The final result is a high-performance site, fully responsive and optimized for all devices.',
          highlights: [
            '22 products across 9 filterable categories',
            'Framer Motion smooth page & section animations',
            'WhatsApp CTA ordering system per product',
            'Infinite-scroll testimonials animation',
            'Fully mobile-responsive hamburger nav',
          ],
          role: 'Frontend Web Developer',
          period: 'Sep 2025 – Dec 2025',
          type: 'Internship',
          ctaText: 'Visit',
          ctaLink: 'https://nuansa-grafika.vercel.app/',
          src: SRC.nuansaGrafika,
          tech: TECH.nuansaGrafika,
        },
        {
          id: 'careerPortal',
          title: 'Career Portal',
          description: 'Job portal platform where job seekers can browse and apply for positions, with a full admin panel.',
          detail:
            'Built with Vue.js on the frontend and Laravel 11 on the backend. Deployed to careers.frisidea.com. Includes user registration, auth, job applications, and full admin control. Configured multi-project server infrastructure and engineered dynamic API integrations with senior developers to deliver real-time data rendering.',
          highlights: [
            'Full-stack: Vue.js frontend + Laravel 11 backend',
            'Deployed to live domain (careers.frisidea.com)',
            'Role-based admin panel for job management',
            '40% improvement in mobile UX via responsive Tailwind',
            'Multi-project server infrastructure configuration',
          ],
          role: 'Fullstack Web Developer',
          period: 'Sep 2024 – May 2025',
          type: 'Internship Contract',
          ctaText: 'Visit',
          ctaLink: 'https://careers.frisidea.com/',
          src: SRC.careerPortal,
          tech: TECH.careerPortal,
        },
        {
          id: 'newsPortal',
          title: 'Personal News Portal',
          description: 'Full-featured blogging platform with comments, likes, trending categories, and YouTube embeds.',
          detail:
            'Built on Laravel 10 with user auth, comment threads, post reactions, category filtering, advanced search by title/date/tag, embedded video support, and role-based admin panel. Features two access tiers: editors (content CRUD only) and administrators (full system access). Developed from Figma UI/UX prototyping all the way to production deployment.',
          highlights: ['Role-based admin: Editor vs Administrator access', 'Advanced search by title, date, and tag', 'Likes, comments & real-time engagement features', 'YouTube & video embed support', 'Full Figma-to-production workflow'],
          role: 'Freelance Fullstack Developer',
          period: 'Dec 2023 – Feb 2024',
          type: 'Freelance',
          ctaText: 'Coming soon',
          ctaLink: '/',
          src: SRC.newsPortal,
          tech: TECH.newsPortal,
        },
        {
          id: 'electionSystem',
          title: 'Realtime Election System',
          description: 'Hierarchical voting system with real-time results, JWT auth, and support for 1,000+ concurrent users.',
          detail:
            'Web-based hierarchical election management system supporting multi-category voting scenarios (e.g., Movie Awards with multiple sub-categories), each sub-election maintaining an independent one-vote-per-user constraint. Built 20+ RESTful API endpoints covering user auth, candidate CRUD, RBAC, automated PDF report generation with charts, and a full VoteLog audit trail. UI designed through low- and high-fidelity Figma wireframes across two iterations before implementation.',
          highlights: [
            'Multi-category voting with cascade election activation',
            'Real-time vote tally via Socket.io',
            'JWT + bcrypt security, Nodemailer email verification',
            '20+ RESTful API endpoints with RBAC (Voter/Admin/Super Admin)',
            'Automated PDF report generation with charts',
            'Sub-300ms API response target, VoteLog audit trail',
          ],
          role: 'Fullstack Developer',
          period: 'Jan 2025 – Sep 2025',
          type: 'University Project',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra',
          src: SRC.electionSystem,
          tech: TECH.electionSystem,
        },
        {
          id: 'onlineCourse',
          title: 'Online Course Website',
          description: 'E-learning platform with a custom REST API, admin panel, and full CRUD for course content.',
          detail: 'React frontend paired with a Node.js + Express API connected to MySQL. Features course browsing, an admin dashboard, and complete content management via REST endpoints.',
          highlights: ['React frontend + Node.js/Express backend', 'Full CRUD for courses via REST API', 'Admin dashboard for content management', 'MySQL relational database architecture'],
          role: 'Fullstack Developer',
          period: '2024',
          type: 'Bootcamp Project',
          ctaText: 'Visit',
          ctaLink: 'https://fe1b-videobelajar.vercel.app/',
          src: SRC.onlineCourse,
          tech: TECH.onlineCourse,
        },
        {
          id: 'portfolio',
          title: 'Portfolio Website',
          description: 'Personal portfolio with smooth page transitions and dynamic animations.',
          detail: 'Built with React.js and Tailwind CSS. Three pages with entrance animations powered by GSAP and Anime.js, plus animated route transitions. Focused on a unique aesthetic that reflects a personal brand.',
          highlights: ['GSAP & Anime.js entrance animations', 'Animated route transitions between pages', 'Multi-language support (EN / ID / DE)', 'Responsive dark-themed design'],
          role: 'Solo Developer',
          period: '2024',
          type: 'Personal Project',
          ctaText: 'Visit',
          ctaLink: 'https://ryan-porto.vercel.app/',
          src: SRC.portfolio,
          tech: TECH.portfolio,
        },
        {
          id: 'chill',
          title: 'Chill — Landing Page',
          description: 'Responsive landing page for a movie streaming concept, built as a bootcamp project.',
          detail: 'Pure CSS responsive layout with a JavaScript-powered burger menu. Focused on clean structure and mobile-first design as an early bootcamp deliverable.',
          highlights: ['Pure CSS responsive layout, no framework', 'JavaScript hamburger menu', 'Mobile-first design approach'],
          role: 'Frontend Developer',
          period: '2024',
          type: 'Bootcamp Project',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/Chill-movie',
          src: SRC.chill,
          tech: TECH.chill,
        },
        {
          id: 'todolist',
          title: 'Todolist App',
          description: 'Mobile-inspired task manager with categorized personal and schedule lists.',
          detail: 'Smartphone-frame UI that organizes tasks into distinct categories. Lightweight vanilla implementation with no dependencies.',
          highlights: ['Smartphone-frame UI concept', 'Categorized task lists', 'Zero dependencies — pure vanilla JS'],
          role: 'Frontend Developer',
          period: '2024',
          type: 'Personal Project',
          ctaText: 'Visit',
          ctaLink: 'https://todolist-zeta-eight-36.vercel.app/',
          src: SRC.todolist,
          tech: TECH.todolist,
        },
        {
          id: 'odrin',
          title: 'Drink Ordering App',
          description: 'Android app for ordering international drinks, built natively with Kotlin.',
          detail:
            'First Android project — Kotlin with SQLite for local data persistence. Implements Material Design principles with Android resource packages for responsive layouts. Users browse a drink menu and place orders through a native Android UI with CRUD operations and optimized query patterns for offline functionality.',
          highlights: ['Native Kotlin Android application', 'SQLite local database with CRUD operations', 'Material Design UI principles', 'Seamless offline functionality'],
          role: 'Android Developer',
          period: 'May 2023',
          type: 'University Project',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/OdrinApp',
          src: SRC.odrin,
          tech: TECH.odrin,
        },
        {
          id: 'cinema',
          title: 'Movie Ticketing App',
          description: 'Console-based Java app for selecting movies and purchasing tickets.',
          detail: 'First executable Java project — simulates a cinema ticketing flow where users pick a film, choose seat type, and receive a summary.',
          highlights: ['First Java executable project', 'Console-based cinema ticketing flow', 'Movie selection and seat type logic'],
          role: 'Developer',
          period: '2022',
          type: 'University Project',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/CinemaTicket',
          src: SRC.cinema,
          tech: TECH.cinema,
        },
      ],
    },
  },

  // ══════════════════════════════════════════════════════════════════════ ID ══
  id: {
    nav: { home: 'Beranda', about: 'Tentang', projects: 'Proyek' },

    home: {
      role: 'Fullstack Developer',
      description: 'Sarjana Teknologi Informasi Komputer · Asia e University. Berpengalaman dalam pengembangan web dan mobile fullstack. Telah menyelesaikan Bootcamp Fullstack Web Developer dan kursus Bahasa Jerman B1.',
      resume: 'Résumé',
      contact: 'Hubungi Saya',
      seeMore: 'Jelajahi',
      cvFile: CV_FILES.id,
    },

    about: {
      title: 'Tentang Saya',
      subtitle: 'Fullstack Developer',
      tagline: 'Web & Mobile · Gamer · Sinema · ',
      certHint: '↑ Klik sertifikat untuk melihat pratinjau',
      downloadCV: 'Unduh CV',
      contact: 'Hubungi Saya',
      profileAlt: 'Muhammad Ryan Cakraningrat',
      cvFile: CV_FILES.id,
      bio: 'Mahasiswa Teknologi Informasi Komputer di Asia e University. Saya membangun aplikasi web dan mobile fullstack — dari prototyping UI/UX hingga backend API dan deployment. Tertarik pada arsitektur yang bersih dan UX yang menarik. Saat ini sedang mendalami programming melalui materi online dan mengeksplorasi penggunaan homeserver untuk berbagai kebutuhan personal.',
      stats: { projects: 'Proyek', internships: 'Pengalaman', certs: 'Sertifikasi' },
      sections: {
        experience: 'Pengalaman Kerja',
        education: 'Pendidikan',
        skills: 'Tech Stack',
        certifications: 'Sertifikasi & Pelatihan',
      },
      experience: [
        {
          role: 'Frontend Web Developer',
          company: 'Nuansa Grafika',
          period: 'Sep 2025 – Des 2025',
          desc: 'Merancang dan mengembangkan website profil perusahaan statis penuh untuk perusahaan desain grafis & percetakan dari awal. Membangun seluruh UI dengan React.js dan Tailwind CSS, mengintegrasikan Framer Motion untuk animasi halus, dan komponen latar belakang partikel animasi kustom.',
          tags: ['React', 'Tailwind CSS', 'Framer Motion', 'JavaScript'],
        },
        {
          role: 'Fullstack Web Developer',
          company: 'Frisidea Tech',
          period: 'Sep 2024 – Mei 2025',
          desc: 'Membangun aplikasi web career page dari awal (frontend, backend, admin panel) menggunakan Vue.js, Tailwind CSS, dan Laravel 11. Dikonfigurasi ke domain live. Mengintegrasikan API dinamis bersama senior developer, meningkatkan UX mobile sebesar 40% via pola Tailwind responsif.',
          tags: ['Vue.js', 'Laravel 11', 'Tailwind', 'MySQL', 'API'],
        },
        {
          role: 'Freelance Fullstack Developer',
          company: 'Portal Berita Personal',
          period: 'Des 2023 – Feb 2024',
          desc: 'Merancang dan mengembangkan portal berita fullstack dari prototyping Figma hingga produksi menggunakan Laravel + Tailwind. Fitur: kategori trending, pencarian lanjutan, embed video, likes/komentar, dan panel admin berbasis peran (editor vs. administrator).',
          tags: ['Laravel', 'MySQL', 'Tailwind', 'Figma', 'RBAC'],
        },
        {
          role: 'Magang Fullstack Android & Web Developer',
          company: 'DPR RI',
          period: 'Jun 2023 – Jul 2023',
          desc: 'Membangun aplikasi absensi Android native (Kotlin + REST API) dan dashboard admin web (CodeIgniter 4) untuk operasional parlemen. Mengoptimalkan skema database, meningkatkan performa query 35%.',
          tags: ['Kotlin', 'Android', 'CodeIgniter 4', 'MySQL', 'REST API'],
        },
      ],
      education: [
        {
          degree: 'Sarjana Teknologi Informasi Komputer',
          school: 'Asia e University (Malaysia)',
          period: 'Sep 2021 – 2026',
          note: 'IPK 3.56 · Double-degree',
        },
        {
          degree: 'Diploma NIIT – Teknologi Informasi',
          school: 'CEP-CCIT, Universitas Indonesia',
          period: 'Sep 2021 – Sep 2023',
          note: 'IPK 3.00',
        },
        {
          degree: 'Bootcamp Fullstack Web Developer',
          school: 'Harisenin.com',
          period: 'Mei 2024 – Okt 2024',
          note: 'Selesai · IPK 4.00',
        },
      ],
      skills: {
        frontend: ['React.js', 'Vue.js', 'Tailwind CSS', 'HTML5', 'CSS3', 'JavaScript', 'GSAP', 'Framer Motion'],
        backend: ['Laravel', 'CodeIgniter 4', 'Node.js', 'Express.js', 'PHP', 'Socket.io'],
        mobile: ['Kotlin', 'Java (Android)', 'Android Studio'],
        database: ['MySQL', 'SQLite', 'MongoDB'],
        tools: ['Git', 'Figma', 'REST API', 'JWT', 'Multer', 'AWS'],
      },
      languages: [
        { lang: 'Indonesia', level: 'Native' },
        { lang: 'Inggris', level: 'Menengah' },
        { lang: 'Jerman', level: 'B1' },
      ],
      certifications: [
        { name: 'AWS re/Start Program', issuer: 'Amazon Web Services', year: '2025', previewLink: null },
        { name: 'Bootcamp Fullstack Developer', issuer: 'Harisenin.com', year: '2024', previewLink: null, id: 'HSBC/FSD/012/20241023049' },
        { name: 'Belajar HTML & CSS Dasar', issuer: 'Codepolitan', year: '2024', previewLink: CERT_LINKS.codepolitan },
        { name: 'Workshop Web Development', issuer: 'DevTown', year: '2023', previewLink: CERT_LINKS.devtown1 },
        { name: 'Sertifikat Magang DPR RI', issuer: 'DPR RI', year: '2023', previewLink: CERT_LINKS.dpr },
        { name: 'Pengantar HTML & CSS', issuer: 'Progate', year: '2021', previewLink: CERT_LINKS.html },
        { name: 'Pengantar Python', issuer: 'Progate', year: '2021', previewLink: CERT_LINKS.python },
      ],
    },

    projects: {
      title: 'Proyek Saya',
      label: 'Portofolio',
      items: [
        {
          id: 'nuansaGrafika',
          title: 'Nuansa Grafika — Profil Perusahaan',
          description: 'Website profil perusahaan statis penuh untuk perusahaan desain grafis & percetakan dengan katalog produk animasi.',
          detail:
            'Dibangun dari nol menggunakan React.js dan Tailwind CSS, dilengkapi animasi Framer Motion dan latar belakang partikel dinamis. Platform ini mengelola katalog terfilter berisi 22 produk dalam 9 kategori, testimoni infinite-scroll, FAQ, dan integrasi Google Maps. Saya merancang sistem pemesanan via WhatsApp dengan CTA khusus per produk dan tombol kontak melayang untuk memudahkan interaksi pelanggan. Hasil akhirnya adalah situs berperforma tinggi yang sepenuhnya responsif di semua perangkat.',
          highlights: [
            '22 produk dalam 9 kategori yang bisa difilter',
            'Animasi halus Framer Motion di seluruh bagian',
            'Sistem CTA pemesanan WhatsApp per produk',
            'Animasi infinite-scroll testimonial pelanggan',
            'Navigasi hamburger responsif mobile penuh',
          ],
          role: 'Frontend Web Developer',
          period: 'Sep 2025 – Des 2025',
          type: 'Magang',
          ctaText: 'Kunjungi',
          ctaLink: 'https://nuansa-grafika.vercel.app/',
          src: SRC.nuansaGrafika,
          tech: TECH.nuansaGrafika,
        },
        {
          id: 'careerPortal',
          title: 'Career Portal',
          description: 'Platform portal kerja tempat pencari kerja bisa melihat dan melamar posisi, dilengkapi panel admin lengkap.',
          detail:
            'Dibangun dengan Vue.js di frontend dan Laravel 11 di backend. Deploy ke careers.frisidea.com. Menangani registrasi pengguna, autentikasi, pengajuan lamaran, dan kendali penuh admin. Mengonfigurasi infrastruktur server multi-proyek dan mengintegrasikan API dinamis bersama developer senior.',
          highlights: [
            'Full-stack: frontend Vue.js + backend Laravel 11',
            'Deploy ke domain live (careers.frisidea.com)',
            'Panel admin berbasis peran untuk manajemen lowongan',
            'Peningkatan UX mobile 40% via Tailwind responsif',
            'Konfigurasi infrastruktur server multi-proyek',
          ],
          role: 'Fullstack Web Developer',
          period: 'Sep 2024 – Mei 2025',
          type: 'Kontrak Magang',
          ctaText: 'Kunjungi',
          ctaLink: 'https://careers.frisidea.com/',
          src: SRC.careerPortal,
          tech: TECH.careerPortal,
        },
        {
          id: 'newsPortal',
          title: 'Portal Berita Personal',
          description: 'Platform blogging lengkap dengan komentar, like, kategori trending, dan embed YouTube.',
          detail:
            'Dibangun di atas Laravel 10 dengan autentikasi, thread komentar, reaksi postingan, filter kategori, pencarian lanjutan berdasarkan judul/tanggal/tag, embed video, dan panel admin berbasis peran. Dua tingkat akses: editor (CRUD konten saja) dan administrator (akses penuh). Dikembangkan dari prototyping UI/UX Figma hingga deployment produksi.',
          highlights: [
            'Admin berbasis peran: akses Editor vs Administrator',
            'Pencarian lanjutan berdasarkan judul, tanggal, dan tag',
            'Likes, komentar & fitur engagement real-time',
            'Dukungan embed YouTube & video',
            'Alur kerja lengkap dari Figma hingga produksi',
          ],
          role: 'Freelance Fullstack Developer',
          period: 'Des 2023 – Feb 2024',
          type: 'Freelance',
          ctaText: 'Segera hadir',
          ctaLink: '/',
          src: SRC.newsPortal,
          tech: TECH.newsPortal,
        },
        {
          id: 'electionSystem',
          title: 'Sistem Pemilihan Realtime',
          description: 'Sistem voting hierarkis dengan hasil real-time, auth JWT, dan dukungan 1.000+ pengguna bersamaan.',
          detail:
            'Sistem manajemen pemilihan hierarkis berbasis web yang mendukung skenario voting multi-kategori (contoh: Film Awards dengan banyak sub-kategori), setiap sub-pemilihan mempertahankan batasan satu suara per pengguna secara independen. Dibangun 20+ endpoint RESTful API mencakup auth pengguna, CRUD kandidat, RBAC, pembuatan laporan PDF otomatis dengan grafik, dan VoteLog audit trail lengkap.',
          highlights: [
            'Voting multi-kategori dengan aktivasi pemilihan bertingkat',
            'Tally suara real-time via Socket.io',
            'Keamanan JWT + bcrypt, verifikasi email Nodemailer',
            '20+ endpoint RESTful API dengan RBAC (Voter/Admin/Super Admin)',
            'Pembuatan laporan PDF otomatis dengan grafik',
            'Target respons API sub-300ms, VoteLog audit trail',
          ],
          role: 'Fullstack Developer',
          period: 'Jan 2025 – Sep 2025',
          type: 'Proyek Universitas',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra',
          src: SRC.electionSystem,
          tech: TECH.electionSystem,
        },
        {
          id: 'onlineCourse',
          title: 'Website Kursus Online',
          description: 'Platform e-learning dengan REST API kustom, panel admin, dan CRUD lengkap untuk konten kursus.',
          detail: 'Frontend React dipasangkan dengan API Node.js + Express yang terhubung ke MySQL. Fitur penelusuran kursus, dasbor admin, dan manajemen konten lengkap via endpoint REST.',
          highlights: ['Frontend React + backend Node.js/Express', 'CRUD lengkap kursus via REST API', 'Dashboard admin untuk manajemen konten', 'Arsitektur database relasional MySQL'],
          role: 'Fullstack Developer',
          period: '2024',
          type: 'Proyek Bootcamp',
          ctaText: 'Kunjungi',
          ctaLink: 'https://fe1b-videobelajar.vercel.app/',
          src: SRC.onlineCourse,
          tech: TECH.onlineCourse,
        },
        {
          id: 'portfolio',
          title: 'Website Portofolio',
          description: 'Portofolio pribadi dengan transisi halaman smooth dan animasi dinamis.',
          detail: 'Dibangun dengan React.js dan Tailwind CSS. Tiga halaman dengan animasi entrance menggunakan GSAP dan Anime.js, plus transisi rute yang dianimasikan. Fokus pada estetika unik yang mencerminkan personal brand.',
          highlights: ['Animasi entrance GSAP & Anime.js', 'Transisi rute animasi antar halaman', 'Dukungan multi-bahasa (EN / ID / DE)', 'Desain dark-themed yang responsif'],
          role: 'Solo Developer',
          period: '2024',
          type: 'Proyek Personal',
          ctaText: 'Kunjungi',
          ctaLink: 'https://ryan-porto.vercel.app/',
          src: SRC.portfolio,
          tech: TECH.portfolio,
        },
        {
          id: 'chill',
          title: 'Chill — Landing Page',
          description: 'Landing page responsif untuk konsep streaming film, dibuat sebagai proyek bootcamp.',
          detail: 'Layout responsif CSS murni dengan menu burger berbasis JavaScript. Fokus pada struktur bersih dan desain mobile-first.',
          highlights: ['Layout responsif CSS murni tanpa framework', 'Menu hamburger JavaScript', 'Pendekatan desain mobile-first'],
          role: 'Frontend Developer',
          period: '2024',
          type: 'Proyek Bootcamp',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/Chill-movie',
          src: SRC.chill,
          tech: TECH.chill,
        },
        {
          id: 'todolist',
          title: 'Aplikasi Todolist',
          description: 'Task manager bergaya mobile dengan daftar personal dan jadwal yang terkategorisasi.',
          detail: 'UI berbingkai smartphone yang mengorganisir tugas ke dalam kategori berbeda. Implementasi vanilla ringan tanpa dependensi.',
          highlights: ['Konsep UI berbingkai smartphone', 'Daftar tugas terkategorisasi', 'Tanpa dependensi — pure vanilla JS'],
          role: 'Frontend Developer',
          period: '2024',
          type: 'Proyek Personal',
          ctaText: 'Kunjungi',
          ctaLink: 'https://todolist-zeta-eight-36.vercel.app/',
          src: SRC.todolist,
          tech: TECH.todolist,
        },
        {
          id: 'odrin',
          title: 'Aplikasi Pesan Minuman',
          description: 'Aplikasi Android untuk memesan minuman internasional, dibangun native dengan Kotlin.',
          detail:
            'Proyek Android pertama — menggunakan Kotlin dengan SQLite untuk penyimpanan data lokal. Mengimplementasikan prinsip Material Design dengan resource package Android. Pengguna menelusuri menu minuman dan melakukan pemesanan melalui UI Android native dengan operasi CRUD dan pola query yang dioptimalkan.',
          highlights: ['Aplikasi Android Kotlin native', 'Database SQLite lokal dengan operasi CRUD', 'Prinsip UI Material Design', 'Fungsionalitas offline yang lancar'],
          role: 'Android Developer',
          period: 'Mei 2023',
          type: 'Proyek Universitas',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/OdrinApp',
          src: SRC.odrin,
          tech: TECH.odrin,
        },
        {
          id: 'cinema',
          title: 'Aplikasi Tiket Bioskop',
          description: 'Aplikasi Java berbasis konsol untuk memilih film dan membeli tiket.',
          detail: 'Proyek Java pertama yang dapat dieksekusi — mensimulasikan alur pembelian tiket bioskop di mana pengguna memilih film, jenis kursi, dan menerima ringkasan.',
          highlights: ['Proyek Java pertama yang dapat dieksekusi', 'Alur tiket bioskop berbasis konsol', 'Logika pemilihan film dan jenis kursi'],
          role: 'Developer',
          period: '2022',
          type: 'Proyek Universitas',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/CinemaTicket',
          src: SRC.cinema,
          tech: TECH.cinema,
        },
      ],
    },
  },

  // ══════════════════════════════════════════════════════════════════════ DE ══
  de: {
    nav: { home: 'Startseite', about: 'Über mich', projects: 'Projekte' },

    home: {
      role: 'Fullstack-Entwickler',
      description: 'Bachelor in Informationstechnologie · Asia e University. Erfahrung in der Full-Stack-Web- und Mobilentwicklung. Kürzlich Fullstack-Web-Bootcamp und Deutschkurs B1 abgeschlossen.',
      resume: 'Lebenslauf',
      contact: 'Kontakt',
      seeMore: 'Entdecken',
      cvFile: CV_FILES.de,
    },

    about: {
      title: 'Über Mich',
      subtitle: 'Fullstack-Entwickler',
      tagline: 'Web & Mobile · Gamer · Kino · Ausbildung in Deutschland angestrebt 🇩🇪',
      certHint: '↑ Zertifikat anklicken zum Vorschauen',
      downloadCV: 'Lebenslauf herunterladen',
      contact: 'Kontakt aufnehmen',
      profileAlt: 'Muhammad Ryan Cakraningrat',
      cvFile: CV_FILES.de,
      bio: 'Student der Informationstechnologie an der Asia e University. Ich entwickle Full-Stack-Web- und Mobilanwendungen – von UI/UX-Prototypen bis hin zu Backend-APIs und Deployment. Besonderes Interesse an sauberer Architektur und exzellenter UX. Derzeit vertiefe ich meine Deutschkenntnisse für zukünftige Karrierechancen in Deutschland.',
      stats: { projects: 'Projekte', internships: 'Erfahrungen', certs: 'Zertifikate' },
      sections: {
        experience: 'Berufserfahrung',
        education: 'Ausbildung',
        skills: 'Tech Stack',
        certifications: 'Zertifikate & Schulungen',
      },
      experience: [
        {
          role: 'Frontend-Webentwickler',
          company: 'Nuansa Grafika',
          period: 'Sep 2025 – Dez 2025',
          desc: 'Entwarf und entwickelte eine vollständig statische Unternehmensprofilwebsite für ein Grafikdesign- und Druckunternehmen von Grund auf. Erstellte die gesamte UI mit React.js und Tailwind CSS, integrierte Framer Motion für flüssige Animationen und eine benutzerdefinierte animierte Partikelhintergrundkomponente.',
          tags: ['React', 'Tailwind CSS', 'Framer Motion', 'JavaScript'],
        },
        {
          role: 'Fullstack-Webentwickler',
          company: 'Frisidea Tech',
          period: 'Sep 2024 – Mai 2025',
          desc: 'Entwicklung einer Career-Page-Webanwendung von Grund auf (Frontend, Backend, Admin-Panel) mit Vue.js, Tailwind CSS und Laravel 11. Deployment auf Live-Domain. API-Integration mit Senior-Entwicklern, mobile UX um 40% verbessert.',
          tags: ['Vue.js', 'Laravel 11', 'Tailwind', 'MySQL', 'API'],
        },
        {
          role: 'Freiberuflicher Fullstack-Entwickler',
          company: 'Persönliches Nachrichtenportal',
          period: 'Dez 2023 – Feb 2024',
          desc: 'Entwicklung eines Full-Stack-Nachrichtenportals von Figma-Prototyp bis Produktion mit Laravel + Tailwind. Trending-Kategorien, erweiterte Suche, Video-Einbettung, Likes/Kommentare und rollenbasiertes Admin-Panel.',
          tags: ['Laravel', 'MySQL', 'Tailwind', 'Figma', 'RBAC'],
        },
        {
          role: 'Praktikant – Fullstack Android & Web',
          company: 'Repräsentantenhaus (DPR RI)',
          period: 'Jun 2023 – Jul 2023',
          desc: 'Native Android-Anwesenheits-App (Kotlin + REST API) und Web-Admin-Dashboard (CodeIgniter 4) für den Parlamentsbetrieb. Datenbankoptimierung mit 35% Leistungsverbesserung.',
          tags: ['Kotlin', 'Android', 'CodeIgniter 4', 'MySQL', 'REST API'],
        },
      ],
      education: [
        {
          degree: 'Bachelor in Informationstechnologie',
          school: 'Asia e University (Malaysia)',
          period: 'Sep 2021 – 2026',
          note: 'Note 3,56 · Doppelabschluss',
        },
        {
          degree: 'Diplom NIIT – Informationstechnologie',
          school: 'CEP-CCIT, Universität Indonesien',
          period: 'Sep 2021 – Sep 2023',
          note: 'Note 3,00',
        },
        {
          degree: 'Fullstack Web Developer Bootcamp',
          school: 'Harisenin.com',
          period: 'Mai 2024 – Okt 2024',
          note: 'Abgeschlossen · Note 4,00',
        },
      ],
      skills: {
        frontend: ['React.js', 'Vue.js', 'Tailwind CSS', 'HTML5', 'CSS3', 'JavaScript', 'GSAP', 'Framer Motion'],
        backend: ['Laravel', 'CodeIgniter 4', 'Node.js', 'Express.js', 'PHP', 'Socket.io'],
        mobile: ['Kotlin', 'Java (Android)', 'Android Studio'],
        database: ['MySQL', 'SQLite', 'MongoDB'],
        tools: ['Git', 'Figma', 'REST API', 'JWT', 'Multer', 'AWS'],
      },
      languages: [
        { lang: 'Indonesisch', level: 'Muttersprache' },
        { lang: 'Englisch', level: 'Mittelstufe' },
        { lang: 'Deutsch', level: 'B1' },
      ],
      certifications: [
        { name: 'AWS re/Start Program', issuer: 'Amazon Web Services', year: '2025', previewLink: null },
        { name: 'Fullstack Developer Bootcamp', issuer: 'Harisenin.com', year: '2024', previewLink: null, id: 'HSBC/FSD/012/20241023049' },
        { name: 'HTML & CSS Grundlagen', issuer: 'Codepolitan', year: '2024', previewLink: CERT_LINKS.codepolitan },
        { name: 'Web Development Workshop', issuer: 'DevTown', year: '2023', previewLink: CERT_LINKS.devtown1 },
        { name: 'Praktikumszertifikat DPR RI', issuer: 'Repräsentantenhaus', year: '2023', previewLink: CERT_LINKS.dpr },
        { name: 'Einführung in HTML & CSS', issuer: 'Progate', year: '2021', previewLink: CERT_LINKS.html },
        { name: 'Einführung in Python', issuer: 'Progate', year: '2021', previewLink: CERT_LINKS.python },
      ],
    },

    projects: {
      title: 'Meine Projekte',
      label: 'Portfolio',
      items: [
        {
          id: 'nuansaGrafika',
          title: 'Nuansa Grafika — Unternehmensprofil',
          description: 'Vollständig statische Unternehmensprofilwebsite für ein Grafikdesign- & Druckunternehmen mit animiertem Produktkatalog.',
          detail:
            'Entwickelt mit React.js und Tailwind CSS, inklusive Framer Motion Animationen und dynamischem Partikel-Hintergrund. Die Plattform umfasst einen filterbaren Katalog mit 22 Produkten in 9 Kategorien, Infinite-Scroll-Testimonials, FAQ-Bereiche und Google Maps-Integration. Ich habe ein WhatsApp-Bestellsystem mit produktspezifischen CTAs und einem schwebenden Kontakt-Button implementiert, um Kundenanfragen zu optimieren. Das Ergebnis ist eine leistungsstarke Website, die vollständig responsiv und für alle Geräte optimiert ist.',
          highlights: [
            '22 Produkte in 9 filterbaren Kategorien',
            'Framer Motion Animationen in allen Bereichen',
            'WhatsApp-CTA-Bestellsystem pro Produkt',
            'Infinite-Scroll-Testimonials-Animation',
            'Vollständig mobile-responsive Hamburger-Navigation',
          ],
          role: 'Frontend-Webentwickler',
          period: 'Sep 2025 – Dez 2025',
          type: 'Praktikum',
          ctaText: 'Besuchen',
          ctaLink: 'https://nuansa-grafika.vercel.app/',
          src: SRC.nuansaGrafika,
          tech: TECH.nuansaGrafika,
        },
        {
          id: 'careerPortal',
          title: 'Career Portal',
          description: 'Jobportal, auf dem Jobsuchende Stellen durchsuchen und sich bewerben können, mit vollständigem Admin-Panel.',
          detail:
            'Vue.js im Frontend, Laravel 11 im Backend. Deployment auf careers.frisidea.com. Nutzerregistrierung, Authentifizierung, Bewerbungen und vollständige Admin-Kontrolle. Multi-Projekt-Serverinfrastruktur konfiguriert und dynamische API-Integrationen mit Senior-Entwicklern umgesetzt.',
          highlights: [
            'Full-Stack: Vue.js Frontend + Laravel 11 Backend',
            'Deployment auf Live-Domain (careers.frisidea.com)',
            'Rollenbasiertes Admin-Panel für Stellenverwaltung',
            '40% Verbesserung der Mobile-UX via Tailwind',
            'Multi-Projekt-Serverinfrastruktur konfiguriert',
          ],
          role: 'Fullstack-Webentwickler',
          period: 'Sep 2024 – Mai 2025',
          type: 'Praktikumsvertrag',
          ctaText: 'Besuchen',
          ctaLink: 'https://careers.frisidea.com/',
          src: SRC.careerPortal,
          tech: TECH.careerPortal,
        },
        {
          id: 'newsPortal',
          title: 'Persönliches Nachrichtenportal',
          description: 'Umfassende Blogging-Plattform mit Kommentaren, Likes, Trending-Kategorien und YouTube-Einbettungen.',
          detail:
            'Auf Laravel 10, mit Nutzer-Auth, Kommentar-Threads, Post-Reaktionen, Kategoriefilterung, erweiterter Suche nach Titel/Datum/Tag, Video-Einbettung und rollenbasiertem Admin-Panel. Zwei Zugangsstufen: Redakteure (nur Inhalts-CRUD) und Administratoren (vollständiger Systemzugriff). Von Figma-Prototyping bis Produktionsdeployment.',
          highlights: [
            'Rollenbasiertes Admin: Redakteur vs. Administrator',
            'Erweiterte Suche nach Titel, Datum und Tag',
            'Likes, Kommentare & Echtzeit-Engagement-Features',
            'YouTube- & Video-Einbettungsunterstützung',
            'Vollständiger Figma-bis-Produktions-Workflow',
          ],
          role: 'Freiberuflicher Fullstack-Entwickler',
          period: 'Dez 2023 – Feb 2024',
          type: 'Freiberuflich',
          ctaText: 'Demnächst',
          ctaLink: '/',
          src: SRC.newsPortal,
          tech: TECH.newsPortal,
        },
        {
          id: 'electionSystem',
          title: 'Echtzeit-Wahlsystem',
          description: 'Hierarchisches Wahlsystem mit Echtzeitergebnissen, JWT-Auth und Unterstützung für 1.000+ gleichzeitige Nutzer.',
          detail:
            'Webbasiertes hierarchisches Wahlverwaltungssystem für Mehrkategorie-Abstimmungsszenarien (z.B. Filmpreise mit mehreren Unterkategorien), jede Teilwahl mit unabhängiger Ein-Stimme-pro-Nutzer-Beschränkung. 20+ RESTful API-Endpunkte für Nutzer-Auth, Kandidaten-CRUD, RBAC, automatische PDF-Berichterstellung mit Diagrammen und VoteLog-Audit-Trail.',
          highlights: [
            'Mehrkategorie-Abstimmung mit Kettenaktivierung',
            'Echtzeit-Stimmtally via Socket.io',
            'JWT + bcrypt Sicherheit, Nodemailer E-Mail-Verifizierung',
            '20+ RESTful API-Endpunkte mit RBAC (Wähler/Admin/Super Admin)',
            'Automatische PDF-Berichterstellung mit Diagrammen',
            'Sub-300ms API-Antwort-Ziel, VoteLog-Audit-Trail',
          ],
          role: 'Fullstack-Entwickler',
          period: 'Jan 2025 – Sep 2025',
          type: 'Universitätsprojekt',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra',
          src: SRC.electionSystem,
          tech: TECH.electionSystem,
        },
        {
          id: 'onlineCourse',
          title: 'Online-Kurs-Website',
          description: 'E-Learning-Plattform mit benutzerdefinierter REST-API, Admin-Panel und vollständigem CRUD.',
          detail: 'React-Frontend mit Node.js + Express API und MySQL. Kursbrowsing, Admin-Dashboard und vollständige Inhaltsverwaltung über REST-Endpunkte.',
          highlights: ['React Frontend + Node.js/Express Backend', 'Vollständiges CRUD für Kurse via REST API', 'Admin-Dashboard für Content-Management', 'Relationale MySQL-Datenbankarchitektur'],
          role: 'Fullstack-Entwickler',
          period: '2024',
          type: 'Bootcamp-Projekt',
          ctaText: 'Besuchen',
          ctaLink: 'https://fe1b-videobelajar.vercel.app/',
          src: SRC.onlineCourse,
          tech: TECH.onlineCourse,
        },
        {
          id: 'portfolio',
          title: 'Portfolio-Website',
          description: 'Persönliches Portfolio mit sanften Seitenübergängen und dynamischen Animationen.',
          detail: 'React.js und Tailwind CSS. Drei Seiten mit Eingangsanimationen durch GSAP und Anime.js sowie animierten Routenübergängen. Fokus auf einzigartiger Ästhetik als persönliche Marke.',
          highlights: ['GSAP & Anime.js Eingangsanimationen', 'Animierte Routenübergänge zwischen Seiten', 'Mehrsprachige Unterstützung (EN / ID / DE)', 'Responsives Dark-Theme-Design'],
          role: 'Solo-Entwickler',
          period: '2024',
          type: 'Persönliches Projekt',
          ctaText: 'Besuchen',
          ctaLink: 'https://ryan-porto.vercel.app/',
          src: SRC.portfolio,
          tech: TECH.portfolio,
        },
        {
          id: 'chill',
          title: 'Chill — Landingpage',
          description: 'Responsive Landingpage für ein Filmstreaming-Konzept, als Bootcamp-Projekt erstellt.',
          detail: 'Reines CSS-Layout mit JavaScript-Burger-Menü. Mobile-First-Design als frühes Bootcamp-Projekt.',
          highlights: ['Reines CSS-Layout ohne Framework', 'JavaScript-Hamburger-Menü', 'Mobile-First-Designansatz'],
          role: 'Frontend-Entwickler',
          period: '2024',
          type: 'Bootcamp-Projekt',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/Chill-movie',
          src: SRC.chill,
          tech: TECH.chill,
        },
        {
          id: 'todolist',
          title: 'Todolist-App',
          description: 'Mobil-inspirierter Aufgabenmanager mit kategorisierten persönlichen Listen.',
          detail: 'Smartphone-Rahmen-UI für kategorisierte Aufgaben. Leichte Vanilla-Implementierung ohne Abhängigkeiten.',
          highlights: ['Smartphone-Rahmen-UI-Konzept', 'Kategorisierte Aufgabenlisten', 'Keine Abhängigkeiten — reines Vanilla JS'],
          role: 'Frontend-Entwickler',
          period: '2024',
          type: 'Persönliches Projekt',
          ctaText: 'Besuchen',
          ctaLink: 'https://todolist-zeta-eight-36.vercel.app/',
          src: SRC.todolist,
          tech: TECH.todolist,
        },
        {
          id: 'odrin',
          title: 'Getränke-Bestell-App',
          description: 'Android-App zum Bestellen internationaler Getränke, nativ mit Kotlin entwickelt.',
          detail:
            'Erstes Android-Projekt — Kotlin mit SQLite für lokale Datenpersistenz. Material Design-Prinzipien mit Android-Ressourcenpaketen. Nutzer durchsuchen Getränkekarte und geben Bestellungen über native Android-UI auf mit CRUD-Operationen und optimierten Abfragemustern.',
          highlights: ['Native Kotlin Android-Anwendung', 'SQLite lokale Datenbank mit CRUD-Operationen', 'Material Design UI-Prinzipien', 'Nahtlose Offline-Funktionalität'],
          role: 'Android-Entwickler',
          period: 'Mai 2023',
          type: 'Universitätsprojekt',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/OdrinApp',
          src: SRC.odrin,
          tech: TECH.odrin,
        },
        {
          id: 'cinema',
          title: 'Kinoticket-App',
          description: 'Konsolenbasierte Java-App zur Filmauswahl und zum Ticketkauf.',
          detail: 'Erstes ausführbares Java-Projekt — Kinoticket-Kauf-Simulation mit Filmauswahl, Sitztyp und Zusammenfassung.',
          highlights: ['Erstes ausführbares Java-Projekt', 'Konsolenbasierter Kinoticket-Kauf-Ablauf', 'Filmauswahl- und Sitztyp-Logik'],
          role: 'Entwickler',
          period: '2022',
          type: 'Universitätsprojekt',
          ctaText: 'GitHub',
          ctaLink: 'https://github.com/RyanCakra/CinemaTicket',
          src: SRC.cinema,
          tech: TECH.cinema,
        },
      ],
    },
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  const t = translations[language];
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
